# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# todo: autopep8, yamlfmt, groovy, regenerate docs, more?
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
#    -   id: trailing-whitespace seems to conflict with black for some reason
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: requirements-txt-fixer
-   repo: https://github.com/fsouza/autoflake8
    rev: v0.2.2
    hooks:
    -   id: autoflake8
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black-jupyter
        # It is recommended to specify the latest version of Python
        # supported by your project here, or alternatively use
        # pre-commit's default_language_version, see
        # https://pre-commit.com/#top_level-default_language_version
        # language_version: python3.8
