apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
    compute-type: fargate
spec:
  serviceAccountName: jenkins-sa-pr
  containers:
  -
    image: "python:3.7"
    imagePullPolicy: "IfNotPresent"
    name: "37-tester"
    resources:
      limits: {}
      requests:
        memory: 4G
    securityContext:
      runAsGroup: 0
      runAsUser: 0
    command:
      - /bin/cat
    tty: true
    volumeMounts:
      - name: workspace-volume
        mountPath: "/home/jenkins/agent"
        readOnly: false
  -
    image: "python:3.8"
    imagePullPolicy: "IfNotPresent"
    name: "38-tester"
    resources:
      limits: {}
      requests:
        memory: 4G
    securityContext:
      runAsGroup: 0
      runAsUser: 0
    command:
      - /bin/cat
    tty: true
    volumeMounts:
      - name: workspace-volume
        mountPath: "/home/jenkins/agent"
        readOnly: false
  -
    image: "python:3.9"
    imagePullPolicy: "IfNotPresent"
    name: "39-tester"
    resources:
      limits: {}
      requests:
        memory: 4G
    securityContext:
      runAsGroup: 0
      runAsUser: 0
    command:
      - /bin/cat
    tty: true
    volumeMounts:
      - name: workspace-volume
        mountPath: "/home/jenkins/agent"
        readOnly: false
  -
    image: "python:3.10"
    imagePullPolicy: "IfNotPresent"
    name: "310-tester"
    resources:
      limits: {}
      requests:
        memory: 4G
    securityContext:
      runAsGroup: 0
      runAsUser: 0
    command:
      - /bin/cat
    tty: true
    volumeMounts:
      - name: workspace-volume
        mountPath: "/home/jenkins/agent"
        readOnly: false
  -
    image: "jenkins/inbound-agent:latest-alpine"
    imagePullPolicy: "IfNotPresent"
    name: "jnlp"
    resources:
      limits: {}
      requests:
        memory: 500M
    volumeMounts:
      - mountPath: "/home/jenkins/agent"
        name: "workspace-volume"
        readOnly: false
  restartPolicy: "Never"
