# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 4 * * 0"
    

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    # https://github.com/marketplace/actions/install-poetry-action
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install dependencies
      run: poetry install
    - name: Test with pytest
      env:
        UMLS_API_KEY: ${{ secrets.UMLS_API_KEY }}
      run: |
        poetry run coverage run --source umlsrat -m pytest -p no:cacheprovider -v --junitxml unittests.xml tests/
        # running again should use cached requests, be super speedy, and also still work
        poetry run python -m pytest -p no:cacheprovider -v --junitxml unittests-cached.xml tests/
